// <auto-generated />
using System;
using ContentPlatform.Ingestion.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContentPlatform.Ingestion.Infrastructure.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    partial class IngestionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ingestion")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContentPlatform.Ingestion.Domain.SeenItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SourceHash")
                        .IsUnique();

                    b.ToTable("seen_items", "ingestion");
                });

            modelBuilder.Entity("ContentPlatform.Ingestion.Domain.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AutoContent")
                        .HasColumnType("bit");

                    b.Property<bool?>("AutoImage")
                        .HasColumnType("bit");

                    b.Property<bool?>("AutoVideo")
                        .HasColumnType("bit");

                    b.Property<string>("Card1x1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardReels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("IngestSince")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastItemHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PollIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Selector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Type");

                    b.ToTable("sources", "ingestion");
                });
#pragma warning restore 612, 618
        }
    }
}
